    in<<"from dronekit import connect, VehicleMode, LocationGlobalRelative\n"
      <<"import time\n"<<"import argparse\n"
      <<"parser = argparse.ArgumentParser(description='Commands vehicle using vehicle.simple_goto.')\n"
      <<"parser.add_argument('--connect', "
      <<"help=\"Vehicle connection target string. If not specified, SITL automatically started and used.\")\n"
      <<"args = parser.parse_args()\n"
      <<"connection_string = args.connect\n"
      <<"sitl = None\n\n"
      <<"if not connection_string:\n"
      <<"   import dronekit_sitl\n"
      <<"   sitl = dronekit_sitl.start_default()\n"
      <<"   connection_string = sitl.connection_string()\n"
      <<"print 'Connecting to vehicle on: %s' % connection_string\n"
      <<"vehicle = connect(connection_string, wait_ready=True)\n";